version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://fast.services.as24.tech/artifactory/api/npm/npm/
    username: ${{secrets.FAST_USER}}
    password: ${{secrets.FAST_TOKEN}}
updates:
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "typescript.web.nextjs.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "typescript.web.express.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "typescript.lambda"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "java.web.springboot.react.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "java.web.springboot.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "java.lambda"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "java.kafka.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "weekly"
    target-branch: "infrastructure.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "npm"
    registries:
      - npm-npmjs
    directory: "/deploy"
    schedule:
      interval: "daily" # TODO: Updated for testing. Ensure this is changed to 'weekly' before merging to production.
    target-branch: "dotnet.core.api.cdk"
    allow:
      - dependency-name: "@autoscout24/aws-cdk"
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "daily" # TODO: Updated for testing. Ensure this is changed to 'weekly' before merging to production.
    target-branch: "dotnet.core.api.cdk"
    update-types:
      - "version-update:semver-major"
      - "version-update:semver-minor"
