name: Update versions
permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      FAST_HTTPAUTH: ${{ secrets.FAST_HTTPAUTH }}
      FAST_TOKEN: ${{ secrets.FAST_TOKEN }}
      FAST_USER: ${{ secrets.FAST_USER }}
      FAST_EMAIL: ${{ secrets.FAST_EMAIL }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: infrastructure.cdk
      - uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Check for updates and upgrade if possible
        id: check-upgrade
        shell: bash {0}
        run: |
          export UPGRADED=0
          export MAIN_LIB=aws-cdk-lib
          export LATEST_CDK=$(npm v $MAIN_LIB version)
          yarn
          npm outdated $MAIN_LIB > /dev/null 2>&1
          if [[ $? == "0" ]]
          then
              echo -e "\e[32m$MAIN_LIB is up-to-date\e[0m"
          else
              for PKG in $MAIN_LIB '@aws-cdk/integ-runner' '@aws-cdk/integ-tests-alpha'
              do
                  # See https://github.com/aws/aws-cdk/issues/23144 for the reason this is needed
                  if [[ $PKG == '@aws-cdk/integ-runner' ]]
                  then
                    export DESIRED_VERSION=$LATEST_CDK
                    # If we mark UPGRADED here it might mess up things because see issue link above
                  else
                    export DESIRED_VERSION=$(npm v $PKG version)
                    UPGRADED=1
                  fi
                  echo -e "\e[34mSpotted an outdated package ${PKG}, the desired version is ${DESIRED_VERSION}\e[0m"
                  yarn upgrade "${PKG}@${DESIRED_VERSION}"
              done
          fi
          echo "LATEST_CDK=${LATEST_CDK}" >> $GITHUB_ENV
          echo "UPGRADED=${UPGRADED}" >> $GITHUB_OUTPUT
      - name: version bump and commit
        if: ${{ steps.check-upgrade.outputs.UPGRADED == 1 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export BRANCH_NAME=deps-update-${{ env.LATEST_CDK }}
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Bump aws-cdk-lib to ${{ env.LATEST_CDK }}"
          yarn version --minor
          git push -u origin $BRANCH_NAME
      - uses: actions/github-script@v8
        if: ${{ steps.check-upgrade.outputs.UPGRADED == 1 }}
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'aws-cdk | Update cdk to ${{ env.LATEST_CDK }}',
              owner,
              repo,
              head: '${{ env.BRANCH_NAME }}',
              base: '${{ github.ref_name }}',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).',
                'Please review and merge after the test run has been completed in Fizz.'
              ].join('\n')
            });
            const issue_number = result.data.number;
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['dependencies','javascript']
            });
